### ISSUE TITLE
i got warning from my VPS

### ISSUE THREAD

**Issue by mehranexpert** [evilsocket/xray#11]
`We've detected an outgoing Denial of Service attack (http://do.co/21Y1Gc1) originating from your Droplet. Specifically, we have detected inbound traffic exceeding 0.01 Mb/s and outbound traffic exceeding 781.34 Mb/s. Due to the traffic’s harmful nature, your Droplet was taken offline; this means it is not connected to the internet and all hosted sites and services are unreachable. We know that this action is disruptive, but it’s necessary to protect you, our network, and the target of your Droplet’s attack.`

am i shouldn't run it on vps ?

**Comment by evilsocket** [comment]
Quoting the README:

> Anonymity and Legal Issues

> The software will rely on your main DNS resolver in order to enumerate subdomains, also, several > connections might be directly established from your host to the computers of the network you're > scanning in order to grab banners from open ports. Technically, you're just connecting to public > > addresses with open ports (and there's no port scanning involved, as such information is grabbed > > indirectly using Shodan API), but you know, someone might not like such behaviour.

Ehm ...

> someone might not like such behaviour

...

**Comment by evilsocket** [comment]
You could try to reduce the number of concurrent consumers ( -consumers option ), let's say to 1 or 2, but if the Droplet has enough hardware resources and bandwidth, I don't know if it's gonna change anything.
