### ISSUE TITLE
.git/.svn/.hg... etc... enumeration

### ISSUE THREAD

**Issue by 0x27** [evilsocket/xray#23]
Enumerating .git/.svn/.hg and other cruft occasionally left on servers is often useful. We have a partial list of files here: https://github.com/HarryR/httphose/blob/master/httphose/common.txt that could be fun to enumerate to find more out about the server.

**Comment by evilsocket** [comment]
this is out of the scope of this tool, use [dirsearch](https://github.com/evilsocket/dirsearch) instead ;)
