### ISSUE TITLE
please make output human readable

### ISSUE THREAD

**Issue by HaxorGaruda** [evilsocket/xray#28]
please make human readable for result ... thanks ...
in this picture i just replace ',' with newline '\n'
![xray](https://user-images.githubusercontent.com/5996055/28239744-16a2d2ca-699d-11e7-938e-90c0c32c1cdd.png)

**Comment by evilsocket** [comment]
are you kidding me? did u try to open your browser on http://localhost:8080/ while the tool is running?

**Comment by HaxorGaruda** [comment]
when scan running and open on browser make your code crash and no result on browser .. 

![xray - chromium_006](https://user-images.githubusercontent.com/5996055/28239806-8a12031a-699e-11e7-8a33-12f8b8925ea8.png)
![Uploading R.3volv3.R — Konsole_006.png…]()

**Comment by Mehran** [comment]
this happen for me in last version . but before i dont have this issue .
