### ISSUE TITLE
panic: open wordlists/default.lst: no such file or directory

### ISSUE THREAD

**Issue by arbazkiraak** [evilsocket/xray#30]
Runnning from /build:

./xray -shodan-key XXXXXXXX -viewdns-key XXXXXXXX -domain xxxxxxxx.com

____  ___
\   \/  /
 \     RAY v 1.0.0b
 /    by Simone 'evilsocket' Margaritelli
/___/\  \
      \_/

Warning: You have 0 query credits.
@ Saving session to hackerone.com-xray-session.json
panic: open wordlists/default.lst: no such file or directory

> /src/github.com/evilsocket/xray/wordlists# ls
all.lst  default.lst  top1mil-20000.lst  top1mil-5000.lst  top1mil.ls

**Comment by evilsocket** [comment]
if you run it from build, you should use -wordlist ../wordlists/default.lst ...

**Comment by arbazkiraak** [comment]
Thanks @evilsocket

**Comment by arbazkiraak** [comment]
I'm Getting Following Output , When i Try to Run .

Server is up and Running . 
![zzzz](https://user-images.githubusercontent.com/13177578/28248242-fcb5fb90-6a5e-11e7-8a99-5c96a0130f0b.PNG)

**Comment by arbazkiraak** [comment]
@evilsocket

**Comment by evilsocket** [comment]
The output is partial, I need the full output.

**Comment by evilsocket** [comment]
btw make sure you have nothing else running on port 8080

**Comment by arbazkiraak** [comment]
Nothing Running on 8080.
@evilsocket 


root@kali:~/go_projects/src/github.com/evilsocket/xray/build# ./xray -shodan-key XXXXXXXXXX -viewdns-key XXXXXXXXXXXXX -domain hackerone.com -wordlist ../wordlists/default.lst
____  ___
\   \/  /
 \     RAY v 1.0.0b
 /    by Simone 'evilsocket' Margaritelli
/___/\  \
      \_/

@ Restoring session from hackerone.com-xray-session.json ...
@ Loaded 4 entries from session file.
Warning: You have 0 query credits.
@ Restoring DNS bruteforcing from 1.36%
@ Web UI running on http://127.0.0.1:8080/

http: panic serving 127.0.0.1:43260: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 3950 [running]:
net/http.(*conn).serve.func1(0xc4204443c0)
	/usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
panic(0xb4f560, 0xc4203c4c10)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb73e40, 0xc4203c8090, 0x7fd3e4674aa8, 0xc42009eb00, 0xc42009eb00, 0x7fd3e4674aa8)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x80
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc4202e01f0, 0x7fd3e4674aa8, 0xc42009eb00, 0x7fd3e4674aa8, 0xc42009eb00)
	<autogenerated>:10 +0x6a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc42009eb00, 0xc8, 0xf6f960, 0xc4202e01f0)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0x125
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc42009eb00, 0xc8, 0xb73e40, 0xc4203c8090)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x8d
main.main.func1(0xc42009eb00)
	/root/go_projects/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x234
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42009eb00)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4201f2d80, 0xc42009eb00)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x62a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4201f2d80, 0xf71560, 0xc420276000, 0xc4201d8000)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x16b
net/http.serverHandler.ServeHTTP(0xc420300000, 0xf71560, 0xc420276000, 0xc4201d8000)
	/usr/lib/go-1.8/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4204443c0, 0xf72160, 0xc420368c40)
	/usr/lib/go-1.8/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce
http: panic serving 127.0.0.1:43262: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 3962 [running]:
net/http.(*conn).serve.func1(0xc420444460)
	/usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
panic(0xb4f560, 0xc4203d28f0)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb73e40, 0xc4202500c0, 0x7fd3e4674aa8, 0xc42040e0b0, 0xc42040e000, 0x7fd3e4674aa8)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x80
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc4203d2180, 0x7fd3e4674aa8, 0xc42040e0b0, 0x7fd3e4674aa8, 0xc42040e0b0)
	<autogenerated>:10 +0x6a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc42040e0b0, 0xc8, 0xf6f960, 0xc4203d2180)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0x125
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc42040e0b0, 0xc8, 0xb73e40, 0xc4202500c0)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x8d
main.main.func1(0xc42040e0b0)
	/root/go_projects/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x234
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42040e0b0)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4201f2d80, 0xc42040e0b0)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x62a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4201f2d80, 0xf71560, 0xc420330000, 0xc42006c900)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x16b
net/http.serverHandler.ServeHTTP(0xc420300000, 0xf71560, 0xc420330000, 0xc42006c900)
	/usr/lib/go-1.8/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420444460, 0xf72160, 0xc4203c0000)
	/usr/lib/go-1.8/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce
http: panic serving 127.0.0.1:43264: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 3965 [running]:
net/http.(*conn).serve.func1(0xc420444dc0)
	/usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
panic(0xb4f560, 0xc4203c5560)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb73e40, 0xc4203e6c30, 0x7fd3e4674aa8, 0xc42009fe40, 0xc42009fe00, 0x7fd3e4674aa8)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x80
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc4203c4d80, 0x7fd3e4674aa8, 0xc42009fe40, 0x7fd3e4674aa8, 0xc42009fe40)
	<autogenerated>:10 +0x6a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc42009fe40, 0xc8, 0xf6f960, 0xc4203c4d80)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0x125
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc42009fe40, 0xc8, 0xb73e40, 0xc4203e6c30)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x8d
main.main.func1(0xc42009fe40)
	/root/go_projects/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x234
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42009fe40)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4201f2d80, 0xc42009fe40)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x62a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4201f2d80, 0xf71560, 0xc4202762a0, 0xc42006cd00)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x16b
net/http.serverHandler.ServeHTTP(0xc420300000, 0xf71560, 0xc4202762a0, 0xc42006cd00)
	/usr/lib/go-1.8/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420444dc0, 0xf72160, 0xc420298900)
	/usr/lib/go-1.8/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce
http: panic serving 127.0.0.1:43266: [map]: [optional]: [xray.Target]: [optional]: [xray.Context]: [optional]: [xray.Machine]: unsupported type: chan interface {}
goroutine 3997 [running]:
net/http.(*conn).serve.func1(0xc4204d2000)
	/usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
panic(0xb4f560, 0xc4203d3230)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.JSON.Render(0xb73e40, 0xc420250720, 0x7fd3e4674aa8, 0xc42040e370, 0xc42040e300, 0x7fd3e4674aa8)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render/json.go:35 +0x80
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/render.(*JSON).Render(0xc4203d2a70, 0x7fd3e4674aa8, 0xc42040e370, 0x7fd3e4674aa8, 0xc42040e370)
	<autogenerated>:10 +0x6a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Render(0xc42040e370, 0xc8, 0xf6f960, 0xc4203d2a70)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:598 +0x125
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).JSON(0xc42040e370, 0xc8, 0xb73e40, 0xc420250720)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:629 +0x8d
main.main.func1(0xc42040e370)
	/root/go_projects/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x234
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc42040e370)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/context.go:110 +0x5a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4201f2d80, 0xc42040e370)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:337 +0x62a
github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4201f2d80, 0xf71560, 0xc4203300e0, 0xc420466400)
	/root/go_projects/src/github.com/evilsocket/xray/vendor/github.com/gin-gonic/gin/gin.go:301 +0x16b

**Comment by arbazkiraak** [comment]
@evilsocket
