### ISSUE TITLE
Web ui/output file

### ISSUE THREAD

**Issue by mikkz** [evilsocket/xray#34]
Hi evilsocket,

Again thanks for this awesome tool.

I have some problem regarding the web ui, i cannot access it even it say that it is running on xxxxxxx:8080 when access it i got `site cannot be reached`

And when i cancel the process, can i still view the json file ? 

Thank you !

**Comment by evilsocket** [comment]
are you sure you're using the correct address? any error logs?

**Comment by mikkz** [comment]
Yes i do, i even tried different address & no error logs.

**Comment by mikkz** [comment]
.
