### ISSUE TITLE
xray docker build installation issue. 

### ISSUE THREAD

**Issue by susantaroy2002** [evilsocket/xray#37]
Hi Team, 

I am trying to setting up the xray in my mac and getting below error, please help me with way out. 

docker build -t xraydocker .
Sending build context to Docker daemon  8.893MB
Step 1/7 : FROM golang:alpine
 ---> 05fe62871090
Step 2/7 : RUN apk add --no-cache git make
 ---> Using cache
 ---> 160439d01c8d
Step 3/7 : RUN go get github.com/evilsocket/xray &&     cd $GOPATH/src/github.com/evilsocket/xray/ &&     make get_glide &&     make install_dependencies &&     go get -u github.com/jteeuwen/go-bindata/... &&     make build
 ---> Running in 640dad4d4888
# github.com/evilsocket/xray
src/github.com/evilsocket/xray/target.go:116:47: not enough arguments in call to t.ctx.Shodan.GetServicesForHost
	have (string, *shodan.HostServicesOptions)
	want (context.Context, string, *shodan.HostServicesOptions)
The command '/bin/sh -c go get github.com/evilsocket/xray &&     cd $GOPATH/src/github.com/evilsocket/xray/ &&     make get_glide &&     make install_dependencies &&     go get -u github.com/jteeuwen/go-bindata/... &&     make build' returned a non-zero code: 2

**Comment by juniorhero** [comment]
Same error 
any fix?

**Comment by juniorhero** [comment]
@evilsocket  I am getting another error now

docker build -t xraydocker .
Sending build context to Docker daemon  8.928MB
Step 1/7 : FROM golang:alpine
 ---> 233ed4ed14bf
Step 2/7 : RUN apk add --no-cache git make
 ---> Using cache
 ---> 218d104f1b80
Step 3/7 : RUN go get github.com/evilsocket/xray &&     cd $GOPATH/src/github.com/evilsocket/xray/ &&     make get_glide &&     make install_dependencies &&     go get -u github.com/jteeuwen/go-bindata/... &&     make build
 ---> Running in 6f6b4e06007d
**make: *** No rule to make target 'get_glide'.  Stop.**
The command '/bin/sh -c go get github.com/evilsocket/xray &&     cd $GOPATH/src/github.com/evilsocket/xray/ &&     make get_glide &&     make install_dependencies &&     go get -u github.com/jteeuwen/go-bindata/... &&     make build' returned a non-zero code: 2
