### ISSUE TITLE
Install Fails with make install_dependencies

### ISSUE THREAD

**Issue by CreativeWolf** [evilsocket/xray#4]
Heya,

Interesting project! 

Here's the error I'm getting while running `make install_dependencies`

> cw@WolfDen:~/go/src/github.com/evilsocket/xray$ make install_dependencies
> glide install
> make: glide: Command not found
> Makefile:15: recipe for target 'install_dependencies' failed
> make: *** [install_dependencies] Error 127

Go Version:

> cw@WolfDen:~/go/src/github.com/evilsocket/xray$ go version
> go version go1.7.5 linux/amd64

Output of ls -la $GOPATH/bin

> cw@WolfDen:~/go/src/github.com/evilsocket/xray$ ls -la $GOPATH/bin
> total 10320
> drwxrwxr-x 2 cw cw     4096 Jul  9 20:04 .
> drwxrwxr-x 5 cw cw     4096 Jul  9 20:04 ..
> -rwxrwxr-x 1 cw cw 10557277 Jul  9 20:04 glide

Appreciate guidance in getting xray up and running :)

Thanks

**Comment by evilsocket** [comment]
can you sudo ldpreload and try again?

**Comment by CreativeWolf** [comment]
Same error:

> cw@WolfDen:~/go/src/github.com/evilsocket/xray$ sudo ldconfig
> [sudo] password for cw: 
> cw@WolfDen:~/go/src/github.com/evilsocket/xray$ make install_dependencies
> glide install
> make: glide: Command not found
> Makefile:15: recipe for target 'install_dependencies' failed
> make: *** [install_dependencies] Error 127

**Comment by evilsocket** [comment]
I do see the glide binary in your GOPATH, so it should work, no idea why it's not .... open new terminal and try again?

**Comment by CreativeWolf** [comment]
Opened new terminal
`sudo ldconfig`
`make install_dependencies`

Same error...

**Comment by madaratech** [comment]
i see same error after setting the environment properly & while running this `make install_dependencies`

**Comment by evilsocket** [comment]
Could you please run:

> $GOPATH/bin/glide -v

**Comment by madaratech** [comment]
````
root@localhost:~/go/src/github.com/evilsocket/xray# $GOPATH/bin/glide -v
glide version 0.13.0-dev
root@localhost:~/go/src/github.com/evilsocket/xray#
`````

**Comment by CreativeWolf** [comment]
> cw@WolfDen:~/go/src/github.com/evilsocket/xray$ $GOPATH/bin/glide -v
> glide version 0.13.0-dev
>

**Comment by evilsocket** [comment]
Ok, now for the last question: 

Did you update your $PATH appending your $GOPATH ? :D

**Comment by madaratech** [comment]
i did this: 
`export GOPATH=$HOME/go` 
then sourced it.

**Comment by CreativeWolf** [comment]
> export PATH=$PATH:$GOPATH/bin

That fixed the issue with make install_dependencies

Now `make build` fails

> cw@WolfDen:~/go/src/github.com/evilsocket/xray$ make build
> go-bindata -o cmd/xray/ui.go -pkg main ui
> make: go-bindata: Command not found
> Makefile:30: recipe for target 'static' failed
> make: *** [static] Error 127

**Comment by evilsocket** [comment]
Add $GOPATH/bin to your $PATH guys ( I added it in my .zshrc for instance ):

    export GOPATH="$HOME/gocode"
    export PATH="$PATH:$GOPATH/bin"

**Comment by CreativeWolf** [comment]
> cw@WolfDen:~/go/src/github.com/evilsocket/xray$ go get -u github.com/jteeuwen/go-bindata/
> cw@WolfDen:~/go/src/github.com/evilsocket/xray$ make build
> go-bindata -o cmd/xray/ui.go -pkg main ui
> make: go-bindata: Command not found
> Makefile:30: recipe for target 'static' failed
> make: *** [static] Error 127
>

**Comment by evilsocket** [comment]
@CreativeWolf read the **README**

**Comment by madaratech** [comment]
with above `install_dependencies` solved, but the final step n error:

```` 
root@localroot:~/go/src/github.com/evilsocket/xray# make build
go-bindata -o cmd/xray/ui.go -pkg main ui
make: go-bindata: Command not found
Makefile:30: recipe for target 'static' failed
make: *** [static] Error 127
```

**Comment by CreativeWolf** [comment]
Thanks, that sorted it!
Appreciate your help =)

**Comment by evilsocket** [comment]
@madaratech you too, read the README!

**Comment by madaratech** [comment]
haha sorry i see it now, and it worked, thanks @evilsocket :)

**Comment by evilsocket** [comment]
- victory dance - 
┏(･o･)┛♪┗ (･o･) ┓
