### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by x0r0n1n** [evilsocket/xray#44]
When I run to build the docker way it says there is no install candidate for get_glide. There is no get_glide objective in the make file so when i get to step three when building it says failed. I know you need to pull glide from github but I'm not familiar enough with go to fix myself. I'm also not familiar enough with Docker but i just seems like somewhere you need to make sure the Dockerfile or Makefile drags down glide because it appears to be missing.

**Comment by jffin** [comment]
I removed from Dokerfile: make get_glide and make install_dependencies.
Looks like it works now.

**Comment by evilsocket** [comment]
fixed with https://github.com/evilsocket/xray/commit/171655741e384f5b9d1ddbc6145a190d2e0af4e6
