### ISSUE TITLE
Contribute Biggest subdomain Wordlist

### ISSUE THREAD

**Issue by AtharavRH** [evilsocket/xray#47]
Hey, I am very much fascinated by your tool. As mentioned by you I would like to contribute the largest wordlist for sub domains.With 881462 common subdomains
[400_blacklist.txt](https://github.com/evilsocket/xray/files/6364386/400_blacklist.txt)

**Comment by evilsocket** [comment]
hey! thanks, why don't you send a pull request adding your file to the wordlists folder?
