### ISSUE TITLE
Make Shodan key static 

### ISSUE THREAD

**Issue by madaratech** [evilsocket/xray#5]
Hey, nice work, and it's just enhancement suggestion as we know **Shodan key** is imp part of the tool, so is it good to make it static and save it in some file and use from it each time, instead of providing each time with argument.

**Comment by evilsocket** [comment]
I thought about it, but I'll explain you why I didn't do that ... let's say I have multiple keys and I need to balance the xray clients among them, it would be very hard to see which key to use ... that is why I kept it a command line argument.

You can just define an environment variable ( export MY_SHODAN_KEY=.... ), save it in your .(zsh|bash)rc and use that.

**Comment by madaratech** [comment]
Okay, thats make sense 👍
