### ISSUE TITLE
Invalid memory 

### ISSUE THREAD

**Issue by Doujinx** [evilsocket/xray#52]
$ ./xray -shodan-key GxoWeVf2CYZuiqEbaeoW6K4hfvIfxR9M -domain facebook.com -wordlist /home/kali/Programs/xray/wordlists/default.lst
____  ___
\   \/  /
 \     RAY v 1.0.0b
 /    by Simone 'evilsocket' Margaritelli
/___/\  \
      \_/

@ Restoring session from facebook.com-xray-session.json ...
@ Loaded 23 entries from session file.
Warning: You have 0 query credits.
@ Restoring DNS bruteforcing from 3.59%
@ Web UI running on http://127.0.0.1:8080/

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6ae290]

goroutine 360 [running]:
github.com/evilsocket/xray.(*Target).scanDomainAsync.func1(0xc0000b5b90, {0xc0005a00a0, 0x10})
        /home/kali/Programs/xray/target.go:79 +0x90
created by github.com/evilsocket/xray.(*Target).scanDomainAsync
        /home/kali/Programs/xray/target.go:76 +0x9a

**Comment by evilsocket** [comment]
use a more updated / recent tool https://github.com/evilsocket/legba
