### ISSUE TITLE
Can't bind to public IP

### ISSUE THREAD

**Issue by madaratech** [evilsocket/xray#6]
All ports are open on the machine, but only localhost is working, when try to bind public ip using `-address` i see this, i tried to change ports as well, for all port get same error! 
```
panic: listen tcp public_ip:8080: bind: cannot assign requested address

goroutine 18 [running]:
main.main.func2()
        /root/go/src/github.com/evilsocket/xray/cmd/xray/main.go:154 +0x23a
created by main.main
        /root/go/src/github.com/evilsocket/xray/cmd/xray/main.go:156 +0xc53
`````

**Comment by evilsocket** [comment]
What do you mean with "public ip" ? Could you please share the command line arguments you are passing to xray?

**Comment by madaratech** [comment]
`./xray -shodan-key my_key -domain trulia.com -address public ip`

here **public ip** means public ip (external) of machine(vps) where am running xray.

**Comment by evilsocket** [comment]
It's not related to xray, it might be your system configuration requiring you to be root, or some limitation of your VPS provider ... if the ip is valid, and permissions are enough, it makes no difference to xray which address you're binding to.

**Comment by madaratech** [comment]
Okay

**Comment by evilsocket** [comment]
Yep I just tested on two of my dedicated servers and it worked without issues ...

**Comment by evilsocket** [comment]
(make sure you're using the correct ip from ifconfig ... also dmesg could help you spot the cause of the issue)

**Comment by madaratech** [comment]
Finally worked thanks for all the support :)

**Comment by evilsocket** [comment]
You're welcome ^_^

**Comment by evilsocket** [comment]
~ victory dance ~

┏(･o･)┛♪┗ (･o･) ┓
